controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

common_api:
    resource: ../src/Controller/Common/Api/
    type: attribute
    prefix: common/api
admin_api:
    resource: ../src/Controller/Admin/Api/
    type: attribute
    prefix: admin/api
public_api:
    resource: ../src/Controller/Public/Api/
    type: attribute
    prefix: public/api
